name: Image Conversion

on:
  push:
    branches:
      - main

jobs:
  convert_and_rename_images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up ImageMagick
      run: sudo apt-get update && sudo apt-get install -y imagemagick
    
    - name: Convert and Rename Images
      run: |
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        committed_image="$(
          git diff-tree --no-commit-id --name-only ${{ $git_hash }} | 
          grep -E '\.(jpg|jpeg|JPG|JPEG|PNG|png)$' |
          head -n 1
        )"

        if [ -z "$committed_image" ]; then
          echo "No image files found in the commit."
          exit 0
        fi

        for folder in follets espurnes barrufets picasoques exploradors vigies; do
          if [ -f "$folder/$committed_image" ]; then
                
                # Temporarily move the image to a different location
                mv "$committed_image" /tmp

                # Remove all other image files in the folder
                rm ./$folder/*.{jpg,jpeg,JPG,JPEG,PNG,png} 2> /dev/null
                
                # Convert the image to PNG and rename it
                convert "/tmp/$committed_image" "$folder/$folder.png"
                echo "Converted and renamed: $image to $folder/$folder.png"
                rm "/tmp/$committed_image"
                echo "Removed old $committed_image"
              fi
            fi
          done
        done

    - name: Commit and Push Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Converted and renamed images"
        git push
      shell: bash
